create table if not exists travel_packages
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name                     VARCHAR,
    passenger_capacity       BIGINT
);

create table if not exists destinations
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name          VARCHAR NOT NULL
);

create table if not exists activities
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name          VARCHAR  NOT NULL,
    description   TEXT    NOT NULL,
    cost          numeric NOT NULL,
    capacity      BIGINT  NOT NULL,
    consumption   BIGINT,
    destination_id   BIGINT
);

create table if not exists passengers
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name          VARCHAR  NOT NULL,
    mobile        VARCHAR  NOT NULL,
    passenger_type     VARCHAR NOT NULL,
    total_balance      numeric NOT NULL,
    utilized_balance    numeric,
    remaining_balance   numeric
);


create table if not exists travel_package_destination_mapping
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    travel_package_id BIGINT NOT NULL,
    destination_id    BIGINT NOT NULL

);

create table if not exists passenger_travel_package_mapping
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    travel_package_id BIGINT NOT NULL,
    passenger_id    BIGINT NOT NULL

);

create table if not exists passenger_travel_package_destination_activity_mapping
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    travel_package_id BIGINT NOT NULL,
    passenger_id    BIGINT NOT NULL,
    destination_id    BIGINT NOT NULL,
    activity_id    BIGINT NOT NULL,
    activity_cost       numeric NOT NULL

);




ALTER TABLE activities
    ADD CONSTRAINT FK_ACTIVITIES_ON_DESTINATIONS FOREIGN KEY (destination_id) REFERENCES destinations (id);

ALTER TABLE travel_package_destination_mapping
    ADD CONSTRAINT FK_TRAVEL_PACKAGES_ON_TRAVEL_PACKAGE_DESTINATION_MAPPING foreign KEY (travel_package_id) REFERENCES travel_packages (id);
   ALTER TABLE travel_package_destination_mapping
    ADD CONSTRAINT FK_DESTINATIONS_ON_TRAVEL_PACKAGE_DESTINATION_MAPPING FOREIGN KEY (destination_id) REFERENCES destinations (id);

ALTER TABLE passenger_travel_package_mapping
    ADD CONSTRAINT FK_TRAVEL_PACKAGES_ON_PASSENGER_TRAVEL_PACKAGE_MAPPING FOREIGN KEY (travel_package_id) REFERENCES travel_packages (id);
ALTER TABLE passenger_travel_package_mapping
    ADD CONSTRAINT FK_PASSENGERS_ON_PASSENGER_TRAVEL_PACKAGE_MAPPING FOREIGN KEY (passenger_id) REFERENCES passengers (id);

ALTER TABLE passenger_travel_package_destination_activity_mapping
    ADD CONSTRAINT FK_TRAVEL_PACKAGES_ON_PASSENGER_TRAVEL_PACKAGE_DESTINATION_ACTIVITY_MAPPING FOREIGN KEY (travel_package_id) REFERENCES travel_packages (id);
ALTER TABLE passenger_travel_package_destination_activity_mapping
    ADD CONSTRAINT FK_PASSENGERS_ON_PASSENGER_TRAVEL_PACKAGE_DESTINATION_ACTIVITY_MAPPING FOREIGN KEY (passenger_id) REFERENCES passengers (id);
ALTER TABLE passenger_travel_package_destination_activity_mapping
    ADD CONSTRAINT FK_DESTINATIONS_ON_PASSENGER_TRAVEL_PACKAGE_DESTINATION_ACTIVITY_MAPPING FOREIGN KEY (destination_id) REFERENCES destinations (id);
ALTER TABLE passenger_travel_package_destination_activity_mapping
    ADD CONSTRAINT FK_ACTIVITIES_ON_PASSENGER_TRAVEL_PACKAGE_DESTINATION_ACTIVITY_MAPPING FOREIGN KEY (activity_id) REFERENCES activities (id);

